url: "https://labs.hackndo.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog
title: "hackndo labs" # the name of your site, e.g. ACME Corp.
author: "Pixis"
twitter_username: hackndolabs
github_username: hackndolabs
lang: en_US
markdown: kramdown

plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from

excerpt_separator: <!--more-->

